server:
  port: 8060

management:
  security:
    enabled: false

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000


#zuul反向代理
zuul:
  ignoredServices: '*'
  routes:
    auth-service:
      path: /auth/**
#      stripPrefix: false
      sensitiveHeaders:
    cbec-service:
      path: /cbec/**
      sensitiveHeaders:
